// ui-frameworks/preact/basics-with-preact-cli/preact-hooks-basics/src/routes/children-and-composition-example.tsx
import { h } from "preact";

interface WrapperProps {
  color: string;
  children: JSX.Element | JSX.Element[];
}

const Wrapper = (props: WrapperProps): h.JSX.Element => {
  return (
    <div className={`super-important-class border-${props.color}`}>
      {props.children}
    </div>
  );
};

const WelcomeDialogue = (): h.JSX.Element => {
  return (
    <Wrapper color="gray">
      <h1>Welcome!</h1>
      <p>Thank you for visiting!</p>
    </Wrapper>
  );
};

export default WelcomeDialogue;

// other/ui-frameworks/solid/solid-basics/src/routes/children-and-composition-example.tsx
import { JSX } from "solid-js";

interface WrapperProps {
  color: string;
  children: JSX.Element | JSX.Element[];
}

const Wrapper = (props: WrapperProps): JSX.Element => {
  return (
    <div class={`super-important-class border-${props.color}`}>
      {props.children}
    </div>
  );
};

const WelcomeDialogue = (): JSX.Element => {
  return (
    <Wrapper color="gray">
      <h1>Welcome!</h1>
      <p>Thank you for visiting!</p>
    </Wrapper>
  );
};

export default WelcomeDialogue;
