// ui-frameworks/react/basics-with-cra/react-hooks-basics/src/pages/landing.tsx
import { Link } from "react-router-dom";

const Landing = (): JSX.Element => {
  return (
    <>
      <h1>React Hooks Basics</h1>
      <Link to="/children-and-composition-example">
        Children and composition
      </Link>
      <Link to="/hooks-useState-example">useState example</Link>
      <Link to="/hooks-useState-map-example">useState map elements</Link>
      <Link to="/hooks-useEffect-cleanup-example">useEffect cleanup</Link>
      <Link to="/hooks-useEffect-fetch-example">useEffect with fetch</Link>
    </>
  );
};

export default Landing;

// other/ui-frameworks/solid/solid-basics/src/routes/landing.tsx
import { JSX } from "solid-js";
import type { Component } from "solid-js";
import { A } from "@solidjs/router";

const Landing: Component = (): JSX.Element => {
  return (
    <>
      <h1>Solid.js Basics</h1>
      <A href="/children-and-composition-example">Children and composition</A>
      <A href="/createSignal-example">createSignal example</A>
      <A href="/createSignal-map-example">createSignal map elements</A>
      <A href="/on-cleanup-example">onCleanup example</A>
      <A href="/resource-example">resource example</A>
      <A href="/ref-binding-example">Ref binding example</A>
    </>
  );
};

export default Landing;
