// other/ui-frameworks/preact/basics-with-preact-cli/preact-hooks-basics/src/routes/landing.tsx
import { h, Fragment } from "preact";
import { Link } from "preact-router/match";

const Landing = (): h.JSX.Element => {
  return (
    <>
      <h1>Preact Hooks Basics</h1>
      <Link href="/children-and-composition-example">
        Children and composition
      </Link>
      <Link href="/hooks-useState-example">useState example</Link>
      <Link href="/hooks-useState-map-example">useState map elements</Link>
      <Link href="/hooks-useEffect-cleanup-example">useEffect cleanup</Link>
      <Link href="/hooks-useEffect-fetch-example">useEffect with fetch</Link>
      <Link href="/hooks-useReducer-example">useReducer example</Link>
      <Link href="/hooks-useReducer-and-useContext-example">
        useContext with useReducer
      </Link>
      <Link href="/hooks-useRef-example">useRef example</Link>
    </>
  );
};

export default Landing;

// other/ui-frameworks/solid/solid-basics/src/routes/landing.tsx
import { JSX } from "solid-js";
import type { Component } from "solid-js";
import { A } from "@solidjs/router";

const Landing: Component = (): JSX.Element => {
  return (
    <>
      <h1>Solid.js Basics</h1>
      <A href="/children-and-composition-example">Children and composition</A>
      <A href="/createSignal-example">createSignal example</A>
      <A href="/createSignal-map-example">createSignal map elements</A>
      <A href="/on-cleanup-example">onCleanup example</A>
      <A href="/resource-example">resource example</A>
      <A href="/ref-binding-example">Ref binding example</A>
    </>
  );
};

export default Landing;
