// other/ui-frameworks/solid/solid-basics/src/routes/landing.tsx
import { JSX } from "solid-js";
import type { Component } from "solid-js";
import { A } from "@solidjs/router";

const Landing: Component = (): JSX.Element => {
  return (
    <>
      <h1>Solid.js Basics</h1>
      <A href="/children-and-composition-example">Children and composition</A>
      <A href="/createSignal-example">createSignal example</A>
      <A href="/createSignal-map-example">createSignal map elements</A>
      <A href="/on-cleanup-example">onCleanup example</A>
      <A href="/resource-example">resource example</A>
      <A href="/ref-binding-example">Ref binding example</A>
    </>
  );
};

export default Landing;

// ui-frameworks/react/basics-with-cra/react-class-basics/src/pages/landing.tsx
import React from "react";
import { Link } from "react-router-dom";

class Landing extends React.Component {
  state = {};
  render() {
    return (
      <>
        <h1>React Class Basics</h1>
        <Link to="/children-and-composition-example">
          Children and composition
        </Link>
        <Link to="/class-cleanup-example">Cleanup</Link>
        <Link to="/class-no-constructor-example">Class (no constructor)</Link>
        <Link to="/class-with-constructor-example">
          Class (with constructor)
        </Link>
        <Link to="/class-lifecycle-example">Lifecycle</Link>
        <Link to="/class-map-example">Map elements</Link>
        <Link to="/class-mount-fetch-example">Mount with fetch</Link>
      </>
    );
  }
}

export default Landing;
